### ISSUE TITLE
I can't seem to get AnimationFrames working for me?

### ISSUE THREAD

**Issue by jonathanfishbein1** [fredcy/elm-defer-command#1]
I attempted to use the AnimationFrame elm library without success as well as this one.  
With this library I have, in my update function

> 

    LoadProblem problemResponse ->
            let
                (ProblemModel routeProblemModelRecord) =
                    case problemResponse of
                        RemoteData.Success routeProblemModel ->
                            routeProblemModel

                        _ ->
                            problemModelInit
                ( deferModel, deferCmd ) =
                    Defer.update
                        (Defer.AddCmd <|
                            setQuillContent
                                { editorId = "routeProblemContentId"
                                , editorContent = routeProblemModelRecord.problemContent
                                }
                        )
                        problemSolutionModel.defer
            in
            TransferRecord
                { problemSolutionModel
                    | webDataRouteProblemModel = problemResponse
                    , defer = deferModel
                    , problemSolutionCurrentFocus = AnimationFrame
                }
                seed
                autoCompleteModel
                currentUserModel
                ! [ Cmd.map DeferMsg deferCmd ]

and in my subscriptions
`        AnimationFrame ->
            Defer.subscriptions problemSolutionModel.defer |> Sub.map DeferMsg`

My current solution is really hacky, where I use 

`Task.attempt QuilElementFocus (Dom.focus "routeProblemContentId")`

to wait for my desired element to be on the DOM.  Where QuilElementFocus 

`| QuilElementFocus (Result Dom.Error ())`
in the error case I keep calling The Task.attempt above, and in in the success case I send data over to JavaScript.  I think there is a problem in how I am using these libraries?  Do you have any suggestions on what I'm doing wrong?  Thanks

**Comment by fredcy** [comment]
I read over the code you provided but I can't really make sense of the context or even figure out what you expected to happen and what actually did happen. Sorry, I probably won't have time to do detailed study of anything more than a complete simple example (http://sscce.org/).
